
project_id = "jkgmgjjtslkozhehwmng"

[functions.send-inspection-notifications]
verify_jwt = true

[functions.notify-inspection-responsible]
verify_jwt = true

[functions.analyze-inspection-media]
verify_jwt = true

[functions.generate-share-token]
verify_jwt = true

[functions.verify-share-token]
verify_jwt = false

